### ISSUE TITLE
Changes on SVN but not on Git

### ISSUE THREAD

**Issue by kevinlangleyjr** [markoheijnen/wordpress-mu-domain-mapping#12]
Seems like the WP SVN and Git repos for this project are out of sync. If you look, the last commit here was merging in my PR back in Dec. 2013 but yet the SVN repo is showing later changes, as late as 4/17/14. 

I'm getting the following errors based on simple issues with the plugin.

https://cloudup.com/cr9tXHuHJW5
https://cloudup.com/cD525c-7Bpn
And because the first two are outputting errors, I then get https://cloudup.com/cr1XYA3G89p when it is trying to do a wp_redirect

I would not mind submitting a PR to fix these, but I'm just hesitant to do so because it doesn't seem like the GH repo is even being kept up to date. If you could get the Git repo to be up to date with the latest changes, I'd gladly patch these and send a PR your way.

Thanks!

**Comment by markoheijnen** [comment]
This is just a fork of wordpress-mu-domain-mapping. So yes it can get out of sync from the original WordPress plugin.

**Comment by kevinlangleyjr** [comment]
My mistake - I did not know this was just a fork of the official plugin. I just thought this was a synced version of the SVN repo from WP.org. Thanks for clarification!
