### ISSUE TITLE
multi domains

### ISSUE THREAD

**Issue by jhirbour** [markoheijnen/wordpress-mu-domain-mapping#3]
I'm trying to setup several blogs all powered by 1 WP install.

domain1.com/blog
domain2.com/blog
etc...
domain65.com/blog

I know I'd have to use an alias in each sites vhost to point them at a comment wordpress install.

I've been unable to get this plugin (or any other) to work with this.

I'm using a fresh install of wordpress 3.5.1 on Centos using PHP 5.x and MySQL. 

Do you know if what I'm trying to accomplish is even possible? If so can you point me at a starting point?

**Comment by markoheijnen** [comment]
You mean that the whole site lives in /blog/? This repo is just a playground to see how I can change it. Till now not really that stable and not sure yet why.

**Comment by jhirbour** [comment]
I have an existing app on all the sites (e-commerce)

my boss has asked me to "add a wordpress blog to each site".  So all the sites would have an Alias in their apache config to point to /var/www/blogs and then blogs would have a multi domain supporting Wp install (ideally).

I was hoping to only have to maintain/update 1 WP install.   I know there is a "network" option in WP  and several different multi domain modules... but can't seem to get any of them to do this.

**Comment by markoheijnen** [comment]
I would go for blog.domain1.com. That would be the easy/best way to make this work.

**Comment by jhirbour** [comment]
yea it's an SEO thing... apparently domain.com/blog ranks higher than blog.domain.com because it's considered site content and not a different site...

Ok thanks for entertaining my rambling question. I posed on r/wordpress on reddit so I'll see what the internet hive mind comes up with.
